<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <RootNamespace>OpenEcu.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenEcu.Core\OpenEcu.Core.csproj" />
    <ProjectReference Include="..\OpenEcu.Transport.Serial\OpenEcu.Transport.Serial.csproj" />
  </ItemGroup>
</Project>
